name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run ESLint
        run: pnpm eslint src

      - name: Build & Compile
        run: pnpm build --verbose
